---
listing:
  type: table
  feed: true
  sort-ui: true
  image-height: 200px
  max-items: 6
toc: false
page-layout: full
---

## Journal Papers

1. Manjunatha, Hemanth, Sri Sadhan Jujjavarapu, and Ehsan T Esfahani.
`Transfer Learning of Motor Difficulty Classification in
Physical Human-Robot Interaction Using Electromyography.` *Journal of
Computing and Information Science in Engineering*, 1–32.

1. Manjunatha, Hemanth, Shrey Pareek, Sri Sadhan Jujjavarapu, Mostafa
Ghobadi, Thenkurussi Kesavadas, and Ehsan T Esfahani. 2021. `Upper Limb
Home-Based Robotic Rehabilitation During COVID-19 Outbreak.` *Frontiers
in Robotics and AI* 8.

1. Manjunatha, Hemanth, Shrey Pareek, Amirhossein H Memar, Thenkurussi
Kesavadas, and Ehsan T Esfahani. 2020. `Effect of Haptic Assistance
Strategy on Mental Engagement in Fine Motor Tasks.` *Journal of Medical
Robotics Research* 5 (01n02): 2041004.

1. Pareek, Shrey, Hemanth Manjunatha, Ehsan T Esfahani, and Thenkurussi
Kesavadas. 2019. `Myotrack: Realtime Estimation of Subject Participation
in Robotic Rehabilitation Using SEMG and IMU.` *IEEE Access* 7:
76030–41.

1. Thammineni, Chaitanya, Hemanth Manjunatha, and Ehsan T Esfahani. 2021.
`Selective Eye-Gaze Augmentation to Enhance Imitation Learning in Atari
Games.` *Neural Computing and Applications*, 1–10.

1. Zhang, Binbin, Jida Huang, Rahul Rai, and Hemanth Manjunatha. 2018. `A
Sequential Sampling Algorithm for Multistage Static Coverage Problems.`
*Journal of Computing and Information Science in Engineering* 18 (2).


## Conference Paper

1. Amir, Behjat, Hemanth Manjunatha, Apurv J. Kumar, Leighton Collins,
Payam Ghassemi, Souma Chowdhury, Karthik Dantu, David Doermann, and
Ehsan T. Esfahani. 2021. `Learning Swarm Tactics Overs Complex Uncertain
Environments.` In *2021 International Symposium on Multi-Robot and
Multi-Agent Systems (MRS)*.

2. Distefano, Joseph P., Hemanth Manjunatha, Souma Chowdhury, Karthik
Dantu, David Doermann, and Ehsan T. Esfahani. 2021. `Using Physiological
Information to Classify Task Difficulty in Human-Swarm Interaction.`
*IEEE/SMC International Conference on System of Systems Engineering*.

3. Manjunatha, Hemanth, Joseph P. Distefano, Payam Ghassemi, Souma
Chowdhury, Karthik Dantu, David Doermann, and Ehsan T. Esfahani. 2020.
`Using Physiological Measurements to Analyze the Tactical Decisions in
Human Swarm Teams.` *IEEE/SMC International Conference on System of
Systems Engineering*.

4. Manjunatha, Hemanth, Joseph P Distefano, Apurv Jani, Payam Ghassemi,
Souma Chowdhury, Karthik Dantu, David Doermann, and Ehsan T Esfahani. `Using Physiological Measurements to Analyze the Tactical
Decisions in Human Swarm Teams.` In *2020 IEEE International Conference
on Systems, Man, and Cybernetics (SMC)*, 256–61. IEEE.

5. Manjunatha, Hemanth, Joseph Distefano, Apurv Jani, Amir Behjat, Payam
Ghassemi, David Doermann, Souma Chowdhury, Karthik Dantu, and Ehsan T.
Esfahani. 2021. `SHaSTA: A Simulator for Human and Swarm Team
Applications.` In.

6. Manjunatha, Hemanth, and Ehsan T Esfahani.`Extracting Interpretable EEG Features from a Deep Learning
Model to Assess the Quality of Human-Robot Co-Manipulation.` In *2021
10th International IEEE/EMBS Conference on Neural Engineering (NER)*,
339–42. IEEE.

7. Manjunatha, Hemanth, Jida Huang, Binbin Zhang, and Rahul Rai. 2016. `A
Sequential Sampling Algorithm for Multi-Stage Static Coverage Problems.`
In *International Design Engineering Technical Conferences and Computers
and Information in Engineering Conference*, 50114:V02BT03A029. American
Society of Mechanical Engineers.

8. Manjunatha, Hemanth, Sri Sadhan Jujjavarapu, and Ehsan T Esfahani.
2020a. `Classification of Motor Control Difficulty Using EMG in Physical
Human-Robot Interaction.` In *2020 IEEE International Conference on
Systems, Man, and Cybernetics (SMC)*, 2708–13. IEEE.


## Book Chapter

1. Manjunatha, Hemanth, and Ehsan T Esfahani. 2020. `Application of
Reinforcement and Deep Learning Techniques in Brain–Machine Interfaces.`
*Advances in Motor Neuroprostheses*, 1–14.

## Under Review

1. Pak, Andrey, Hemanth Manjunatha, Dimitar Filev, and Panagiotis Tsiotras `CARNet: A Dynamic Autoencoder for Learning Latent Dynamics in
Autonomous Driving Tasks.` *arXiv Preprint arXiv:2205.08712*.

1. Manjunatha, Hemanth, Amir Memar, and Ehsan Esfahani. 2018.
`Classification of Task Type and Reaction Time of Operator in Simulated
Multiple Robot Tele-Exploration.` *Frontiers in Human Neuroscience* 12.
